# affcopy
# Autogenerated from man page /usr/share/man/man1/affcopy.1.gz
complete -c affcopy -s d -d 'Print debugging information as well'
complete -c affcopy -s h -d 'Help, print this message'
complete -c affcopy -s L -d 'Recompress pages (preen) with LZMA (smaller but slower)'
complete -c affcopy -s m -d 'Just copy the missing segments'
complete -c affcopy -s V -d 'Print the program version and exit'
complete -c affcopy -s v -d 'Verbose: print each file as it is copied'
complete -c affcopy -o vv -d 'Very verbose: print each segment as it is copied'
complete -c affcopy -s x -d 'Don\'t verify hashes on reads'
complete -c affcopy -o Xn -d 'Recompress pages (preen) with zlib level n'
complete -c affcopy -s y -d 'Don\'t verify writes'
complete -c affcopy -s z -d 'ZAP (delete).  Copy even if the destination exists. RE '
complete -c affcopy -s k -d 'Specify private key for signing'
complete -c affcopy -s c -d 'Specify a X'
complete -c affcopy -s n -d 'Read notes to accompany the copy from standard in'

