# affcompare
# Autogenerated from man page /usr/share/man/man1/affcompare.1.gz
complete -c affcompare -s e -d 'Just report about existence (use with -r)'
complete -c affcompare -s p -d 'Report about the results of preening'
complete -c affcompare -s r -d 'dir1 dir2  Recursively compare what\'s in dir1 with dir2, and report what\'s in…'
complete -c affcompare -s s -d 'Check to see if named files are on Amazon S3. RE . PP Other options: . RS'
complete -c affcompare -s a -d 'Print what\'s the same (all)'
complete -c affcompare -s b -d 'Print the numbers of differing sectors'
complete -c affcompare -s c -d 'Print the contents of differing sectors'
complete -c affcompare -s h -d 'Show help page'
complete -c affcompare -s m -d 'Just report about the data (ignore metadata)'
complete -c affcompare -s P -d 'Just examine the differences on page \'n\''
complete -c affcompare -s q -d 'Quiet.  No output except for errors'
complete -c affcompare -s V -d 'Just print the version number and exit'
complete -c affcompare -s v -d 'Verbose.  Show each file as it is compared'

