# affcat
# Autogenerated from man page /usr/share/man/man1/affcat.1.gz
complete -c affcat -s s -d 'Output the named segment, instead of the image data'
complete -c affcat -s p -d 'Just output page number  nnn'
complete -c affcat -s S -d 'Just output data sector number  nnn.  Sector #0 is the first sector'
complete -c affcat -s q -d 'Quiet mode'
complete -c affcat -s n -d 'Noisy mode.  Tell when pages are skipped'
complete -c affcat -s l -d 'List all the segment names, rather than outputting data'
complete -c affcat -s L -d 'List Long.  Prints segment names, lengths, and args'
complete -c affcat -s d -d 'Debug mode.  Print the page numbers to stderr as data goes to stdout'
complete -c affcat -s b -d 'Output BADFALG for bad blocks (default is to output NULLs)'
complete -c affcat -s v -d 'Just print the version number and exit'
complete -c affcat -s r -d 'Seek to the given byte offset and output count characters in each file; may b…'

