# affix
# Autogenerated from man page /usr/share/man/man1/affix.1.gz
complete -c affix -s y -d 'Actually modify the files; normally just reports the problems'
complete -c affix -s v -d 'Just print the version number and exit'

