# affsegment
# Autogenerated from man page /usr/share/man/man1/affsegment.1.gz
complete -c affsegment -s c -d 'Create AFF files if they do not exist'
complete -c affsegment -o ssegval -d 'Sets the value of a segment; may be repeated'
complete -c affsegment -o psegname -d 'Prints the contents of the segment name for each file'
complete -c affsegment -s V -d 'Just print the version number and exit'
complete -c affsegment -o dname -d 'Delete segment \'name\''
complete -c affsegment -s h -s '?' -d 'Print this message'
complete -c affsegment -s Q -d 'interpert 8-byte segments as a 64-bit value'
complete -c affsegment -s A -d 'Print the 32-bit arg, not the segment value'
complete -c affsegment -s x -d 'Print the segment as a hex string. RE . PP Setting the segment values: . RS'
complete -c affsegment -o sname -d 'Take the new value of segment \'name\' from stdin'
complete -c affsegment -o sname/arg -d 'Sets segment \'name\' arg to be \'arg\' (may be repeated). RE '

