# affsign
# Autogenerated from man page /usr/share/man/man1/affsign.1.gz
complete -c affsign -s n -d 'Ask for a chain-of-custody note'
complete -c affsign -s v -d 'Just print the version number and exit. RE . PP Signature Options: . RS'
complete -c affsign -s k -d 'Specify private key for signing'
complete -c affsign -s c -d 'Specify a X'
complete -c affsign -s Z -d 'ZAP (remove) all signature segments'

