# affstats
# Autogenerated from man page /usr/share/man/man1/affstats.1.gz
complete -c affstats -s m -d 'Print all output in megabytes'
complete -c affstats -s V -d 'Just print the version number and exit'

