# affuse
# Autogenerated from man page /usr/share/man/man1/affuse.1.gz
complete -c affuse -s d -s o -d 'Enable debug output (implies in -f)'
complete -c affuse -s f -d 'Foreground operation'
complete -c affuse -s s -d 'Disable multi-threaded operation'

