# affverify
# Autogenerated from man page /usr/share/man/man1/affverify.1.gz
complete -c affverify -s a -d 'Print all segments'
complete -c affverify -s V -d 'Just print the version number and exit'
complete -c affverify -s v -d Verbose

