# affxml
# Autogenerated from man page /usr/share/man/man1/affxml.1.gz
complete -c affxml -s j -d 'Just print information about segname (may be repeated)'
complete -c affxml -s s -d 'Output \'stats\' for the file data (may a long time)'
complete -c affxml -s V -d 'Just print the version number and exit'
complete -c affxml -s x -d 'Don\'t include the infile filename in output'

