# afp_client
# Autogenerated from man page /usr/share/man/man1/afp_client.1.gz
complete -c afp_client -s u -l user -d 'Log in using <username>'
complete -c afp_client -s p -l pass -d 'If you specify a \'-\' as the password, you will be prompted for it'
complete -c afp_client -s o -l port -d 'Use TCP portnum instead of the default, 548'
complete -c afp_client -s V -l volumepassword -d 'Use this if the volume you\'re accessing uses a volume password (a very weak f…'
complete -c afp_client -s v -l version -d 'Specify the AFP version that will be used for a mount.  For AFP 2'
complete -c afp_client -s a -l uam -d 'Set the authentication method, to one of: No User Authent'
complete -c afp_client -s m -l map -d 'Set the method used to map local to server UID and GIDs'

