# arp-fingerprint
# Autogenerated from man page /usr/share/man/man1/arp-fingerprint.1.gz
complete -c arp-fingerprint -s h -d 'Display a brief usage message and exit'
complete -c arp-fingerprint -s v -d 'Display verbose progress messages'
complete -c arp-fingerprint -s o -d 'Pass specified options to arp-scan'
complete -c arp-fingerprint -s I -l interface -s I -l numeric -d '(-N)'
complete -c arp-fingerprint -s l -d 'Fingerprint all hosts on the local network'

