# bpfc
# Autogenerated from man page /usr/share/man/man8/bpfc.8.gz
complete -c bpfc -s i -l input -d 'Read BPF assembly instruction from an input file or from stdin'
complete -c bpfc -s p -l cpp -d 'Pass the bpf program through the C preprocessor before reading it in bpfc'
complete -c bpfc -s D -l define -d 'Add macro definition for the C preprocessor to use it within bpf file'
complete -c bpfc -s f -l format -d 'Specify a different output format than the default that is netsniff-ng compat…'
complete -c bpfc -s b -l bypass -d 'Bypass basic filter validation when emitting opcodes'
complete -c bpfc -s V -l verbose -d 'Be more verbose and display some bpfc debugging information'
complete -c bpfc -s d -l dump -d 'Dump all supported instructions to stdout'
complete -c bpfc -s v -l version -d 'Show version information and exit'
complete -c bpfc -s h -l help -d 'Show user help and exit'

