# cgps
# Autogenerated from man page /usr/share/man/man1/cgps.1.gz
complete -c cgps -s '?' -s h -l help
complete -c cgps -s V -l version
complete -c cgps -s D -l debug
complete -c cgps -s l -l llfmt
complete -c cgps -s s -l silent
complete -c cgps -s m -l magtrack
complete -c cgps -s u -l units
complete -c cgps -s d -l kmldir
complete -c cgps -l device
complete -c cgps -l host
complete -c cgps -s i -l initialize
complete -c cgps -l port
complete -c cgps -l sleep

