# create-native-map
# Autogenerated from man page /usr/share/man/man1/create-native-map.1.gz
complete -c create-native-map -l autoconf-header -d 'HEADER is a header file name in the syntax typically used with the C   #inclu…'
complete -c create-native-map -l autoconf-member -d 'Specify that any access to   MEMBER should be wrapped within a   #ifdef HAVE_…'
complete -c create-native-map -l exclude-native-symbol -d 'SYMBOL is a   [DllImport] -marked method that should  not have a prototype ge…'
complete -c create-native-map -l impl-header -d 'Insert a   #include statement within the generated   . c file for   HEADER '
complete -c create-native-map -l impl-macro -d 'Insert a  #define statement within the generated  . c file'
complete -c create-native-map -l library -d 'Create prototypes for  [DllImport] -marked methods which reference the native…'
complete -c create-native-map -l public-header -d 'Insert a   #include statement within the generated   . h file for   HEADER '
complete -c create-native-map -l public-macro -d 'Insert a  #define statement within the generated  . h file'
complete -c create-native-map -l rename-member -d 'This is used when   FROM is a C macro, and thus must be altered in order to b…'
complete -c create-native-map -o marked -d 'not have a prototype generated for it'
complete -c create-native-map -l rename-namespace -d 'By default, the C "namespace" (symbol prefix) is the C# namespace; types  wit…'
complete -c create-native-map -o decorated -d 'MapAttribute properties: NativeType Contains the corresponding C type'

