# crunch
# Autogenerated from man page /usr/share/man/man1/crunch.1.gz
complete -c crunch -s b
complete -c crunch -s c
complete -c crunch -s d
complete -c crunch -s e
complete -c crunch -s f
complete -c crunch -s i
complete -c crunch -s l -s t -s l -s t
complete -c crunch -s m -s p -s p
complete -c crunch -s o
complete -c crunch -s q
complete -c crunch -s r -s r -s s -s s -s r
complete -c crunch -s u
complete -c crunch -s z

