# dave
# Autogenerated from man page /usr/share/man/man1/dave.1p.gz
complete -c dave -o debug -d el
complete -c dave -s h -d el
complete -c dave -o man -d el
complete -c dave -s p -d el
complete -c dave -s u -d el
complete -c dave -o tmpdir -d el

