# dirb
# Autogenerated from man page /usr/share/man/man1/dirb.1.gz
complete -c dirb -s a -d 'Specify your custom USER_AGENT.  (Default is: "Mozilla/4'
complete -c dirb -s c -d 'Set a cookie for the HTTP request'
complete -c dirb -s f -d 'Fine tunning of NOT_FOUND (404) detection'
complete -c dirb -s H -d 'Add a custom header to the HTTP request'
complete -c dirb -s i -d 'Use case-insensitive Search'
complete -c dirb -s l -d 'Print "Location" header when found'
complete -c dirb -s N -d 'Ignore responses with this HTTP code'
complete -c dirb -s o -d 'Save output to disk'
complete -c dirb -s p -d 'Use this proxy.  (Default port is 1080)'
complete -c dirb -s P -d 'Proxy Authentication'
complete -c dirb -s r -d 'Don\'t Search Recursively'
complete -c dirb -s R -d 'Interactive Recursion.  (Ask in which directories you want to scan)'
complete -c dirb -s S -d 'Silent Mode.  Don\'t show tested words.  (For dumb terminals)'
complete -c dirb -s t -d 'Don\'t force an ending \'/\' on URLs'
complete -c dirb -s u -d 'Username and password to use'
complete -c dirb -s v -d 'Show Also Not Existant Pages'
complete -c dirb -s w -d 'Don\'t Stop on WARNING messages'
complete -c dirb -s x -d 'Amplify search with the extensions on this file'
complete -c dirb -s X -d 'Amplify search with this extensions'
complete -c dirb -s z

