# dmitry
# Autogenerated from man page /usr/man/man1/dmitry.1.gz
complete -c dmitry -s o -d 'Create an ascii text output of the results to the "filename" specified'
complete -c dmitry -s i -d 'Perform an Internet Number whois lookup on the target'
complete -c dmitry -s w -d 'Perform a whois lookup on the \'host\' target'
complete -c dmitry -s n -d 'Retrieve netcraft'
complete -c dmitry -s s -d 'Perform a SubDomain search on the specified target'
complete -c dmitry -s e -d 'Perform an EmailAddress search on the specified target'
complete -c dmitry -s p -d 'Perform a TCP Portscan on the host target'
complete -c dmitry -s f -d 'This option will cause the TCP Portscan module to report/display output of fi…'
complete -c dmitry -s b -d 'This option will cause the TCP Portscan module to output Banners if they are …'
complete -c dmitry -s t -d 'This sets the Time To Live (TTL) of the Portscan module when scanning individ…'

