# dns2tcpc
# Autogenerated from man page /usr/share/man/man1/dns2tcpc.1.gz
complete -c dns2tcpc -s h -d 'Help Menu'
complete -c dns2tcpc -s c -d 'Enable DNS compression'
complete -c dns2tcpc -s z -d 'Use this domain as endpoint'
complete -c dns2tcpc -s d -d 'Change debug level.  Levels available are 1, 2 or 3'
complete -c dns2tcpc -s r -d 'Remote resource to access'
complete -c dns2tcpc -s k -d 'Pre shared key used for authentication (identification)'
complete -c dns2tcpc -s f -d 'Configuration file to use'
complete -c dns2tcpc -s T -d 'Request type to use.  Actually only KEY and TXT requests are supported'
complete -c dns2tcpc -s e -d 'Command to execute, I/O are redirected in the tunnel'
complete -c dns2tcpc -s l -d 'Local port accepting incomming connections (or - for stdin on UNIX systems)'
complete -c dns2tcpc -s t -d 'Maximum DNS server\'s answer delay in seconds'

