# dns2tcpd
# Autogenerated from man page /usr/share/man/man1/dns2tcpd.1.gz
complete -c dns2tcpd -s h -d 'Help Menu'
complete -c dns2tcpd -s F -d 'Run in foreground'
complete -c dns2tcpd -s i -d 'IP address to bind (default 0. 0. 0. 0)'
complete -c dns2tcpd -s f -d 'Configuration file to use'
complete -c dns2tcpd -s p -d 'File where our pid will be written'
complete -c dns2tcpd -s d -d 'Change debug level.  Levels available are 1, 2 or 3'

