# dupemap
# Autogenerated from man page /usr/share/man/man1/dupemap.1.gz
complete -c dupemap -s d -d 'Use database as an on-disk database to read from or write to'
complete -c dupemap -s I -d 'Reads input files from file in addition to those listed on the command line'
complete -c dupemap -s m -d 'Ignore files below this size'

