# ewfinfo
# Autogenerated from man page /usr/share/man/man1/ewfinfo.1.gz
complete -c ewfinfo -s A -d 'the codepage of header section, options: ascii (default), windows-874, window…'
complete -c ewfinfo -s d -d 'the date format, options: ctime (default), dm (day/month), md (month/day), is…'
complete -c ewfinfo -s e -d 'only show EWF read error information'
complete -c ewfinfo -s f -d 'specify the output format, options: text (default), dfxml'
complete -c ewfinfo -s h -d 'shows this help'
complete -c ewfinfo -s i -d 'only show EWF acquiry information'
complete -c ewfinfo -s m -d 'only show EWF media information'
complete -c ewfinfo -s v -d 'verbose output to stderr'
complete -c ewfinfo -s V -d 'print version El ENVIRONMENT None FILES None EXAMPLES -literal # ewfinfo \\-d …'

