# ewfmount
# Autogenerated from man page /usr/share/man/man1/ewfmount.1.gz
complete -c ewfmount -s f -d 'specify the input format, options: raw (default), files (restricted to logica…'
complete -c ewfmount -s h -d 'shows this help'
complete -c ewfmount -s v -d 'verbose output to stderr'
complete -c ewfmount -s V -d 'print version'
complete -c ewfmount -s X -d 'extended options to pass to sub system El ENVIRONMENT None FILES None EXAMPLE…'

