# ewfrecover
# Autogenerated from man page /usr/share/man/man1/ewfrecover.1.gz
complete -c ewfrecover -s A -d 'the codepage of header section, options: ascii (default), windows-874, window…'
complete -c ewfrecover -s h -d 'shows this help'
complete -c ewfrecover -s l -d 'logs recover errors and the digest (hash) to the log filename'
complete -c ewfrecover -s p -d 'the process buffer size (default is the chunk size)'
complete -c ewfrecover -s t -d 'the target file to recover to (default is recover)'
complete -c ewfrecover -s v -d 'verbose output to stderr'
complete -c ewfrecover -s V -d 'print version'
complete -c ewfrecover -s x -d 'use the chunk data instead of the buffered read and write functions'

