# ewfverify
# Autogenerated from man page /usr/share/man/man1/ewfverify.1.gz
complete -c ewfverify -s A -d 'the codepage of header section, options: ascii (default), windows-874, window…'
complete -c ewfverify -s d -d 'calculate additional digest (hash) types besides md5, options: sha1, sha256'
complete -c ewfverify -s f -d 'specify the input format, options: raw (default), files (restricted to logica…'
complete -c ewfverify -s h -d 'shows this help'
complete -c ewfverify -s l -d 'logs verification errors and the digest (hash) to the log filename'
complete -c ewfverify -s p -d 'the process buffer size (default is the chunk size)'
complete -c ewfverify -s q -d 'quiet shows minimal status information'
complete -c ewfverify -s v -d 'verbose output to stderr'
complete -c ewfverify -s V -d 'print version'
complete -c ewfverify -s w -d 'zero sectors on checksum error (mimic EnCase like behavior)'
complete -c ewfverify -s x -d 'use the chunk data instead of the buffered read and write functions'

