# ex
# Autogenerated from man page /usr/share/man/man1/ex.1p.gz
complete -c ex -o ccommand -d 'Specify an initial command to be executed in the first edit buffer loaded fro…'
complete -c ex -s r -d 'Recover the named files (see the EXTENDED DESCRIPTION section)'
complete -c ex -s R -d 'Set  readonly edit option'
complete -c ex -s s -d 'Prepare R ex for batch use by taking the following actions: . RS 10'
complete -c ex -o ttagstring -d 'Edit the file containing the specified R tagstring ; see R "ctags"'
complete -c ex -s v -d 'Begin in visual mode (see R "vi")'
complete -c ex -s c -d 'Specify an initial command to be executed in the first edit buffer loaded fro…'
complete -c ex -s t -d 'option is not specified, all other options, the EXINIT variable, and any '
complete -c ex -s w -d 'Set the value of the window editor option to size '
complete -c ex -s 1 -d 'addr1 ,c addr2 ,c addr2 + count'
complete -c ex -s i -d '(interactive mode).  Editing shall be resumed when the program exits'
complete -c ex -s m
complete -c ex -s e -d 'option of sed '
complete -c ex -s x -d 'option, which did encryption based on the algorithm found in the historical c…'
complete -c ex -s 2 -d 'Two lines before the current line'

