# flowtop
# Autogenerated from man page /usr/share/man/man8/flowtop.8.gz
complete -c flowtop -s 4 -l ipv4 -d 'Display IPv4 flows'
complete -c flowtop -s 6 -l ipv6 -d 'Display IPv6 flows'
complete -c flowtop -s T -l tcp -d 'Display TCP flows'
complete -c flowtop -s U -l udp -d 'Display UDP and UDP-lite flows'
complete -c flowtop -s D -l dccp -d 'Display DCCP flows'
complete -c flowtop -s I -l icmp -d 'Display ICMP version 4 and version 6 flows'
complete -c flowtop -s S -l sctp -d 'Display SCTP flows'
complete -c flowtop -s n -l no-dns -d 'Don\'t perform hostname lookup'
complete -c flowtop -s G -l no-geoip -d 'Don\'t perform GeoIP lookup'
complete -c flowtop -s s -l show-src -d 'Also show source information of the flow, not only destination information'
complete -c flowtop -s b -l bits -d 'Show flow rates in bits per second instead of bytes per second'
complete -c flowtop -s u -l update -d 'The built-in database update mechanism will be invoked to get Maxmind\'s lates…'
complete -c flowtop -s t -l interval -d 'Flow info refresh interval in seconds, default is 1s'
complete -c flowtop -s v -l version -d 'Show version information and exit'
complete -c flowtop -s h -l help -d 'Show user help and exit'

