# gd2i
# Autogenerated from man page /usr/share/man/man1/gd2i.1.gz
complete -c gd2i -l extra-check -d 'Report ignore entries, from an existing \'list'
complete -c gd2i -l syntax-check -d 'Report syntax error found when processing an existing \'list. ignore\' file'
complete -c gd2i -l quiet -d 'Used to disable progress and other information which is normally written to s…'
complete -c gd2i -l version -d 'Display the tool\'s version number'
complete -c gd2i -l help -d 'Show help about the command-line options.  EXIT STATUS'

