# gendarme
# Autogenerated from man page /usr/share/man/man1/gendarme.1.gz
complete -c gendarme -l config -d 'Specify the rule sets and rule settings.  Default is \'rules. xml\''
complete -c gendarme -l set -d 'Specify a rule set from configfile.  Defaults to \'default\''
complete -c gendarme -l log -d 'Save the report, as a text file, to the specified file'
complete -c gendarme -l xml -d 'Save the report, formatted as XML, to the specified file'
complete -c gendarme -l html -d 'Save the report, formatted as HTML, to the specified file'
complete -c gendarme -l console -d 'Write the defects on stdout'
complete -c gendarme -l ignore -d 'Do not report defects listed in the specified file'
complete -c gendarme -l limit -d 'Stop reporting after N defects are found'
complete -c gendarme -l severity -d 'Filter the reported defects to include the specified severity levels'
complete -c gendarme -l confidence -d 'Filter the reported defects to include the specified confidence levels'
complete -c gendarme -l quiet -d 'Used to disable progress and other information which is normally written to s…'
complete -c gendarme -l v -d 'When present additional progress information is written to stdout'
complete -c gendarme -l version -d 'Display Gendarme\'s version number'

