# get-oui
# Autogenerated from man page /usr/share/man/man1/get-oui.1.gz
complete -c get-oui -s h -d 'Display a brief usage message and exit'
complete -c get-oui -s f -d 'Write the output to the specified file instead of the default  ieee-oui. txt'
complete -c get-oui -s u -d 'Use the specified URL to fetch the raw OUI data from instead of the default  …'
complete -c get-oui -s v -d 'Display verbose progress messages.  FILES'

