# get-iab
# Autogenerated from man page /usr/share/man/man1/get-iab.1.gz
complete -c get-iab -s h -d 'Display a brief usage message and exit'
complete -c get-iab -s f -d 'Write the output to the specified file instead of the default  ieee-iab. txt'
complete -c get-iab -s u -d 'Use the specified URL to fetch the raw IAB data from instead of the default  …'
complete -c get-iab -s v -d 'Display verbose progress messages.  FILES'

