# gnome-firmware
# Autogenerated from man page /usr/share/man/man1/gnome-firmware.1.gz
complete -c gnome-firmware -s h -l help -d 'Show help options'
complete -c gnome-firmware -l help-all -d 'Show all help options'
complete -c gnome-firmware -l help-gtk -d 'Show GTK+ Options . SS "Application Options:"'
complete -c gnome-firmware -s v -l verbose -d 'Show extra debugging information'
complete -c gnome-firmware -l display -d 'X display to use'

