# gpscsv
# Autogenerated from man page /usr/share/man/man1/gpscsv.1.gz
complete -c gpscsv -s '?' -s h -l help -d 'Show help information and exit'
complete -c gpscsv -s c -l class -d 'Select the JSON class messages of type MCLASS.  Default is TPV'
complete -c gpscsv -l cvt-isotime -d 'Convert fields named "time" from ISO time to UNIX time'
complete -c gpscsv -s D -l debug -d 'Set debug level to LVL.  Default 0'
complete -c gpscsv -l device -d 'The DEVICE on the gpsd to connect to.  Defaults to all'
complete -c gpscsv -s f -o fields -d 'The FIELDS from the JSON message to dump to the output'
complete -c gpscsv -l file -d 'Read JSON from FILE instead of from gpsd'
complete -c gpscsv -l header -d 'Set header style to HEADER'
complete -c gpscsv -l host -d 'Connect to the gpsd on HOST.  Defaults to localhost'
complete -c gpscsv -s n -l count -d 'Exit after outputting COUNT records.  Set COUNT to 0 to disable'
complete -c gpscsv -l port -d 'Use PORT to connect to gpsd.  Defaults to 2947'
complete -c gpscsv -l separator -d 'Use SEPARATOR as the field separator'
complete -c gpscsv -s V -l version -d 'Show gpscsv version, and exit'
complete -c gpscsv -s x -l seconds -d 'Exit after SECONDS number of seconds have passed'

