# gpsmon
# Autogenerated from man page /usr/share/man/man1/gpsmon.1.gz
complete -c gpsmon -s '?' -s h -l help -d 'Print a usage message and exit'
complete -c gpsmon -s a -l nocurses -d 'Enables a special debugging mode that does not use screen painting'
complete -c gpsmon -s d -l debug -d 'Enable packet-getter debugging output and is probably only useful to develope…'
complete -c gpsmon -s l -l logfile -d 'Set up logging to a specified file (FILE) to start immediately on device open'
complete -c gpsmon -s L -l list -d 'Lists a table showing which GPS device types this gpsmon has built-in support…'
complete -c gpsmon -s n -l nmea -d 'Force gpsmon to request NMEA0183 packets instead of the raw data stream from …'
complete -c gpsmon -s t -l type -d 'Set a fallback type (TYPE)'
complete -c gpsmon -s x -d 'of gpsctl(1).  X'

