# gpsplot
# Autogenerated from man page /usr/share/man/man1/gpsplot.1.gz
complete -c gpsplot -s '?' -s h -l help -d 'Print a usage message and exit'
complete -c gpsplot -s d -l debug -d 'Set debug level to LVL'
complete -c gpsplot -l device -d 'The DEVICE on the gpsd to connect to.  Defaults to all'
complete -c gpsplot -l fields -d 'The code for the fields to plot'
complete -c gpsplot -l file -d 'Read JSON from FILE instead of from gpsd'
complete -c gpsplot -l host -d 'Connect to the gpsd on HOST (server).  Defaults to localhost'
complete -c gpsplot -l plottype -d 'The type of plot to make'
complete -c gpsplot -s n -l count -d 'Exit after COUNT plot messages'
complete -c gpsplot -s p -l port -d 'Use PORT to connect to gpsd.  Defaults to 2947'
complete -c gpsplot -s V -l version -d 'Print the program version and exit'
complete -c gpsplot -s x -l seconds -d 'Wait for SECONDS seconds before exiting.  Set to zero to diable.  Default 0'

