# gpsprof
# Autogenerated from man page /usr/share/man/man1/gpsprof.1.gz
complete -c gpsprof -s '?' -s h -l help -d 'Print a usage message and exit'
complete -c gpsprof -s d -l dumpfile -d 'Dump the plot data, without attached gnuplot code, to a specified file for po…'
complete -c gpsprof -l debug -d 'Sets debug level'
complete -c gpsprof -s l -l logfile -d 'Dump the raw JSON reports collected from the device to the specified FILE'
complete -c gpsprof -s n -l wait -d 'Sets the number of seconds to sample.  The default is 100'
complete -c gpsprof -s r -l redo -d 'Replot from a JSON logfile (such as -l, logfile produces) on standard input'
complete -c gpsprof -s S -l subtitle -d 'Sets a text string to be included in the plot as a subtitle'
complete -c gpsprof -s t -l title -d 'Sets a text string to be the plot title.  This will replace the default title'
complete -c gpsprof -s T -l terminal -d 'Add a terminal type setting into the gnuplot code'
complete -c gpsprof -s f -l formatter -d 'option sets the plot type.  Currently the following plot types are defined:'

