# gpssubframe
# Autogenerated from man page /usr/share/man/man1/gpssubframe.1.gz
complete -c gpssubframe -s '?' -s h -l help -d '-Print a usage message and exit'
complete -c gpssubframe -s c -l count -d 'Exit after COUNT subframe messages'
complete -c gpssubframe -l device -d 'Connect to device DEVICE on gpsd host'
complete -c gpssubframe -s D -l debug -d 'Set debug level to LVL'
complete -c gpssubframe -l file -d 'Read JSON from FILE instead of from gpsd'
complete -c gpssubframe -l host -d 'Connect to gpsd on host HOST'
complete -c gpssubframe -l port -d 'Connect to gpsd on port PORT'
complete -c gpssubframe -l progress -d 'Print progress reports as messages are received'
complete -c gpssubframe -l satpos -d 'Compute GPS satellite positions before exit'
complete -c gpssubframe -l time -d 'Compute satellite position at time SEC in POSIX seconds'
complete -c gpssubframe -l test -d 'Run --satpos selftest code'
complete -c gpssubframe -s V -l version -d 'Print the program version, then exit'
complete -c gpssubframe -s x -l seconds -d 'Seconds of messages to parse.  0 to disable'
complete -c gpssubframe -o Print

