# gpxlogger
# Autogenerated from man page /usr/share/man/man1/gpxlogger.1.gz
complete -c gpxlogger -s '?' -s h -l help -d 'Print a summary of options and then exit'
complete -c gpxlogger -s d -l daemonize -d 'Run as a daemon in background'
complete -c gpxlogger -s D -l debug -d 'Sets the debug level; it is primarily for troubleshooting'
complete -c gpxlogger -s i -l interval -d 'A new track is created if there\\*(Aqs no fix written for an interval of SECON…'
complete -c gpxlogger -s l -l exports -d 'List all possible options for -e, --export'
complete -c gpxlogger -s m -l minmove -d 'Sets a minimum move distance in meters (it may include a fractional decimal p…'
complete -c gpxlogger -s r -l reconnect -d 'Retry when GPSd loses the fix.  Without -r, gpxlogger would quit in this case'
complete -c gpxlogger -s V -l version -d 'Dump the package version and exit'
complete -c gpxlogger -s e -l export -d 'one of the colon-terminated method names from the'
complete -c gpxlogger -s f -l output -d 'option, which directs output to a specified logfile'

