# ifpps
# Autogenerated from man page /usr/share/man/man8/ifpps.8.gz
complete -c ifpps -s d -l dev -d 'Networking device to fetch statistics from, for example eth0, wlan0'
complete -c ifpps -s n -l num-cpus -d 'Set maximum number of top hitter CPUs (in terms of time spent in system/user …'
complete -c ifpps -s t -l interval -d 'Statistics refresh interval in milliseconds, default is 1000ms'
complete -c ifpps -s c -l csv -d 'Output (once) the ncurses data to the terminal as  gnuplot (1)-ready data'
complete -c ifpps -s l -l loop -d 'Continuously output the terminal data after a refresh interval'
complete -c ifpps -s m -l median -d 'Show median values across all CPUs for CPU load, interrupts (per interval and…'
complete -c ifpps -s o -l omit-header -d 'Omit printing the CSV header.  This option is only available if -c is given'
complete -c ifpps -s p -l promisc -d 'Turn on promiscuous mode for the given networking device'
complete -c ifpps -s P -l percentage -d 'Show percentage of current throughput in relation to theoretical line rate'
complete -c ifpps -s W -l no-warn -d 'Suppress possible warnings in the ncurses output, e. g'
complete -c ifpps -s v -l version -d 'Show version information'
complete -c ifpps -s h -l help -d 'Show user help'

