# inetsim
# Autogenerated from man page /usr/share/man/man1/inetsim.1.gz
complete -c inetsim -l config -d 'The configuration file to use, default is conf/inetsim'
complete -c inetsim -l version -d 'Output version information'
complete -c inetsim -l data-dir -d 'The data directory to use, default is data/ in the current directory'
complete -c inetsim -l log-dir -d 'The log directory to use, default is log/ in the current directory'
complete -c inetsim -l report-dir -d 'The report directory to use, default is report/ in the current directory'
complete -c inetsim -l bind-address -d 'The \\s-1IP\\s0 address to bind services to'
complete -c inetsim -l max-childs -d 'The maximum number of child processes (number of parallel connections) for ea…'
complete -c inetsim -l user -d 'User to run services.  Default is \'nobody\''
complete -c inetsim -l faketime-init-delta -d 'Initial number of seconds (positive or negative) relative to current date/tim…'
complete -c inetsim -l faketime-auto-delay -d 'Number of seconds to wait before incrementing or decrementing fake time by am…'
complete -c inetsim -l faketime-auto-incr -d 'Number of seconds by which fake time is incremented or decremented at regular…'
complete -c inetsim -l session -d 'Session name to use, default is the \\s-1PID\\s0 of the parent process'

