# isql
# Autogenerated from man page /usr/share/man/man1/isql.1.gz
complete -c isql -s b -d 'Run isql in non-interactive batch mode'
complete -c isql -o dDELIMITER -d 'Delimits columns with delimiter'
complete -c isql -o xHEX -d 'Delimits columns with HEX, which is a hexadecimal code of the delimiting char…'
complete -c isql -s w -d 'Format the result as HTML table'
complete -c isql -s c -d 'Output the names of the columns on the first row'
complete -c isql -o mNUM -d 'Limit the column display width to NUM characters'
complete -c isql -o lLOCALE -d 'Sets locale to LOCALE'
complete -c isql -s q -d 'Wrap the character fields in double quotes'
complete -c isql -s 3 -d 'Use the ODBC 3 calls'
complete -c isql -s n -d 'Use the new line processing'
complete -c isql -s e -d 'Use the SQLExecDirect instead of Prepare'
complete -c isql -s k -d 'Use SQLDriverConnect'
complete -c isql -s v -d 'Turn on the verbose mode, where the errors are fully described'
complete -c isql -l version -d 'Prints the program version and exits'
complete -c isql -s d -s x
complete -c isql -o LNUM -d 'Alter the maximum number of characters displayed from a character field to NU…'

