# jcat-tool
# Autogenerated from man page /usr/share/man/man1/jcat-tool.1.gz
complete -c jcat-tool -s h -l help -d 'Show help options . SS "Application Options:"'
complete -c jcat-tool -l version -d 'Print the version number'
complete -c jcat-tool -s v -l verbose -d 'Print verbose debug statements'
complete -c jcat-tool -l basename -d 'Only consider the basename for the ID'
complete -c jcat-tool -l disable-time-checks -d 'Disable time checks when verifying'
complete -c jcat-tool -l public-key -d 'Location of public key used for verification'
complete -c jcat-tool -l public-keys -d 'Location of public key directories used for verification'
complete -c jcat-tool -l prefix -d 'Prefix for import and output files'
complete -c jcat-tool -l kind -d 'Kind for blob, e. g.  `gpg`'
complete -c jcat-tool -l appstream-id -d 'Appstream ID for blob, e. g.  `com. bbc`'
complete -c jcat-tool -l keyring -d 'Keyring location, e. g.  `/var/lib/fwupd`'

