# lp
# Autogenerated from man page /usr/share/man/man1/lp.1p.gz
complete -c lp -s c -d 'Exit only after further access to any of the input files is no longer required'
complete -c lp -o ddest -d 'Specify a string that names the destination (\\c R dest )'
complete -c lp -s m -d 'Send mail (see R "mailx") after the files have been printed'
complete -c lp -o ncopies -d 'Write R copies number of copies of the files, where R copies is a positive de…'
complete -c lp -o ooption -d 'Specify printer-dependent or class-dependent R option s'
complete -c lp -s s -d 'Suppress messages from R lp '
complete -c lp -o ttitle -d 'Write R title on the banner page of the output'
complete -c lp -s o -d 'option values'
complete -c lp -s d -d 'Specify a string that names the destination (c dest )'
complete -c lp -s n -d 'Write copies number of copies of the files, where copies is a positive decima…'
complete -c lp -s t -d 'Write title on the banner page of the output'
complete -c lp -s w -d 'Write a message on the user\'s terminal after the files have been printed'

