# lrelease-qt3
# Autogenerated from man page /usr/share/man/man1/lrelease-qt3.1.gz
complete -c lrelease-qt3 -o help -d 'Display the usage and exit'
complete -c lrelease-qt3 -o nocompress -d 'Do not compress the . qm files'
complete -c lrelease-qt3 -o verbose -d 'Explain what is being done'
complete -c lrelease-qt3 -o version -d 'Display the version of lrelease and exit.  USAGE Here is an example '

