# lupdate-qt3
# Autogenerated from man page /usr/share/man/man1/lupdate-qt3.1.gz
complete -c lupdate-qt3 -o help -d 'Display the usage and exit'
complete -c lupdate-qt3 -o noobsolete -d 'Drop all obsolete strings'
complete -c lupdate-qt3 -o verbose -d 'Explain what is being done'
complete -c lupdate-qt3 -o version -d 'Display the version of lupdate and exit.  USAGE Here is an example '

