# magicrescue
# Autogenerated from man page /usr/share/man/man1/magicrescue.1.gz
complete -c magicrescue -s b -d 'Default: 1'
complete -c magicrescue -s d -d 'Mandatory.   Output directory for found files'
complete -c magicrescue -s r -d 'Mandatory.   Recipe name, file, or directory'
complete -c magicrescue -s I -d 'Reads input files from file in addition to those listed on the command line'
complete -c magicrescue -s M -d 'Produce machine-readable output to stdout.   output_mode can be: . RS 7'
complete -c magicrescue -s O -d 'Resume from the specified offset in the first device'

