# mailx
# Autogenerated from man page /usr/share/man/man1/mailx.1p.gz
complete -c mailx -s e -d 'Test for the presence of mail in the system mailbox'
complete -c mailx -s f -d 'Read messages from the file named by the R file operand instead of the system…'
complete -c mailx -s F -d 'Record the message in a file named after the first recipient'
complete -c mailx -s H -d 'Write a header summary only'
complete -c mailx -s i -d 'Ignore interrupts.  (See also  ignore . )'
complete -c mailx -s n -d 'Do not initialize from the system default start-up file'
complete -c mailx -s N -d 'Do not write an initial header summary'
complete -c mailx -o 's\\0subject' -d 'Set the  Subject header field to R subject '
complete -c mailx -s s -d 'subject option shall be required on all systems'
complete -c mailx -s u -d 'Read the system mailbox of the login name user '
complete -c mailx -s c -d 'command shall be valid'

