# masscan
# Autogenerated from man page /usr/share/man/man8/masscan.8.gz
complete -c masscan -l range
complete -c masscan -s p -l ports -o p80 -s p -o p80 -l ports
complete -c masscan -l banners
complete -c masscan -l rate
complete -c masscan -s c -l conf
complete -c masscan -l resume -l append-output
complete -c masscan -l echo
complete -c masscan -s e -l adapter
complete -c masscan -l adapter-ip
complete -c masscan -l adapter-port
complete -c masscan -l adapter-mac
complete -c masscan -l router-mac
complete -c masscan -l ping
complete -c masscan -l exclude
complete -c masscan -l excludefile
complete -c masscan -l iflist
complete -c masscan -l retries
complete -c masscan -l nmap
complete -c masscan -l pcap-payloads -l nmap-payloads
complete -c masscan -l http-user-agent
complete -c masscan -l open-only
complete -c masscan -l pcap
complete -c masscan -l packet-trace
complete -c masscan -l pfring
complete -c masscan -l resume-index
complete -c masscan -l resume-count -l shards
complete -c masscan -l rotate
complete -c masscan -l rotate-offset
complete -c masscan -l rotate-dir
complete -c masscan -l seed
complete -c masscan -l regress
complete -c masscan -l ttl
complete -c masscan -l wait
complete -c masscan -l offline
complete -c masscan -o sL -l shard
complete -c masscan -l interactive -l output-format -l output-filename
complete -c masscan -o oB -l readscan
complete -c masscan -o oX
complete -c masscan -o oG
complete -c masscan -o oJ
complete -c masscan -o oL

