# memcat
# Autogenerated from man page /usr/share/man/man1/memcat.1.gz
complete -c memcat -l servers -d 'or via the environment variable: MEMCACHED_SERVERS For a full list of operati…'
complete -c memcat -l help

