# memcapable
# Autogenerated from man page /usr/share/man/man1/memcapable.1.gz
complete -c memcapable -s h -d 'Specify the hostname to connect to.  The default is localhost'
complete -c memcapable -s p -d 'Specify the port number to connect to.  The default is 11211'
complete -c memcapable -s c -d 'Generate a coredump when it detects an error from the server'
complete -c memcapable -s v -d 'Print out the comparison when it detects an error from the server'
complete -c memcapable -s t -d 'Set the timeout from an IO operation to/from the server to n seconds.  HOME'

