# memexist
# Autogenerated from man page /usr/share/man/man1/memexist.1.gz
complete -c memexist -l servers -d 'or via the environment variable: MEMCACHED_SERVERS If you do not specify eith…'
complete -c memexist -l help

