# memflush
# Autogenerated from man page /usr/share/man/man1/memflush.1.gz
complete -c memflush -l servers -d 'or via the environment variable: MEMCACHED_SERVERS For a full list of operati…'
complete -c memflush -l help

