# memping
# Autogenerated from man page /usr/share/man/man1/memping.1.gz
complete -c memping -l servers -d 'or via the environment variable: MEMCACHED_SERVERS If you do not specify eith…'
complete -c memping -l help

