# memrm
# Autogenerated from man page /usr/share/man/man1/memrm.1.gz
complete -c memrm -l servers -d 'or via the environment variable: MEMCACHED_SERVERS For a full list of operati…'
complete -c memrm -l help

