# memslap
# Autogenerated from man page /usr/share/man/man1/memslap.1.gz
complete -c memslap -l servers -d 'or via the environment variable: MEMCACHED_SERVERS For a full list of operati…'
complete -c memslap -l help

