# memstat
# Autogenerated from man page /usr/share/man/man1/memstat.1.gz
complete -c memstat -l servers -d 'or via the environment variable: \'MEMCACHED_SERVERS, --args\' which can be use…'
complete -c memstat -l help
complete -c memstat -l analyze

