# memtouch
# Autogenerated from man page /usr/share/man/man1/memtouch.1.gz
complete -c memtouch -l servers -d 'or via the environment variable: MEMCACHED_SERVERS If you do not specify eith…'
complete -c memtouch -l help

