# nbtscan
# Autogenerated from man page /usr/share/man/man1/nbtscan.1.gz
complete -c nbtscan -s v -d 'Verbose output.  Print all names received from each host'
complete -c nbtscan -s d -d 'Dump packets.  Print whole packet contents'
complete -c nbtscan -s e -d 'Format output in /etc/hosts format'
complete -c nbtscan -s l -d 'Format output in lmhosts format.  Cannot be used with -v, -s or  -h options'
complete -c nbtscan -s t -d 'Wait timeout seconds for response.  Default 1'
complete -c nbtscan -s b -d 'Output throttling'
complete -c nbtscan -s r -d 'Use local port 137 for scans.  Win95 boxes respond to this only'
complete -c nbtscan -s q -d 'Suppress banners and error messages'
complete -c nbtscan -s s -d 'Script-friendly output'
complete -c nbtscan -s h -d 'Print human-readble names for services.   Can only be used with -v option'
complete -c nbtscan -s m -d 'Number of retransmits.  Default 0'
complete -c nbtscan -s f -d 'Take IP addresses to scan from file "filename"'

