# ncrack
# Autogenerated from man page /usr/share/man/man1/ncrack.1.gz
complete -c ncrack -o iX -o oX
complete -c ncrack -o iN -o oN
complete -c ncrack -o iL
complete -c ncrack -s p -d option
complete -c ncrack -l exclude
complete -c ncrack -l excludefile
complete -c ncrack -o sV -d option
complete -c ncrack -o sL -d 'option (see below for explanation)'
complete -c ncrack -s m -d 'which is defined with the format:'
complete -c ncrack -s g -d 'as follows:'
complete -c ncrack -s d -d 'option if you want even more verbose output'
complete -c ncrack -l --- -l --- -d 'cl=7, CL=80, at=0, cd=0, cr=30, to=0'
complete -c ncrack -s T -d 'While the fine-grained timing controls discussed in the previous section are …'
complete -c ncrack -o T3 -d 'does nothing'
complete -c ncrack -o T4 -d ' Even then, this is mostly advised for services residing in the local network'
complete -c ncrack -o T5 -d 'is not recommended, unless you absolutely know what you are doing'
complete -c ncrack -o T0 -d and
complete -c ncrack -o T1 -d 'may be useful for avoiding IDS alerts, they will take an extraordinarily long…'
complete -c ncrack -l connection-limit
complete -c ncrack -s U
complete -c ncrack -s P
complete -c ncrack -l user
complete -c ncrack -l pass
complete -c ncrack -l passwords-first
complete -c ncrack -l pairwise
complete -c ncrack -o oA
complete -c ncrack -s v
complete -c ncrack -o d10 -d 'sets level ten'
complete -c ncrack -l nsock-trace
complete -c ncrack -l log-errors
complete -c ncrack -l append-output
complete -c ncrack -l resume
complete -c ncrack -s f
complete -c ncrack -s 6
complete -c ncrack -l datadir
complete -c ncrack -l proxy
complete -c ncrack -o 'V;' -l version
complete -c ncrack -o 'h;' -l help

