# neard
# Autogenerated from man page /usr/share/man/man8/neard.8.gz
complete -c neard -l version -d 'Print the neard software version and exit'
complete -c neard -l help -d 'Print neard\'s available options and exit'
complete -c neard -l debug -d 'Sets how much information neard sends to the log destination (usually syslog\'…'
complete -c neard -l plugin -d 'Load these plugins only'
complete -c neard -l noplugin -d 'Never load these plugins'
complete -c neard -l nodaemon -d 'Do not daemonize'

