# netdiscover
# Autogenerated from man page /usr/share/man/man8/netdiscover.8.gz
complete -c netdiscover -s i -d 'The network interface to sniff and inject packets'
complete -c netdiscover -s r -d 'Scan a given range instead of auto scan'
complete -c netdiscover -s l -d 'Scan ranges contained on the given file'
complete -c netdiscover -s p -d 'Enable passive mode'
complete -c netdiscover -s m -d 'Scan a list of known MACs and host names'
complete -c netdiscover -s F -d 'Customize pcap filter expression (default: "arp")'
complete -c netdiscover -s s -d 'Sleep given time in milliseconds between each ARP request injection'
complete -c netdiscover -s c -d 'Number of times to send each ARP request'
complete -c netdiscover -s n -d 'Last IP octet of the source IP used for scanning'
complete -c netdiscover -s d -d 'Ignore configuration files at home dir (for autoscan and fast mode only)'
complete -c netdiscover -s f -d 'Enable fast mode scan.  This will only scan for . 1, . 100 and '
complete -c netdiscover -s P -d 'Produces an output suitable to be redirected into a file or to be parsed by a…'
complete -c netdiscover -s L -d 'Similar to -P but continue program execution to capture ARP packets passively…'
complete -c netdiscover -s N -d 'Do not print header.  Only valid when -P or -L is enabled'
complete -c netdiscover -s S -d '(DEPRECATED) Enable sleep time suppression between each request'

