# netmask
# Autogenerated from man page /usr/share/man/man1/netmask.1.gz
complete -c netmask -s h -l help -d 'Print a summary of the options'
complete -c netmask -s v -l version -d 'Print the version number'
complete -c netmask -s d -l debug -d 'Print status/progress information'
complete -c netmask -s s -l standard -d 'Output address/netmask pairs'
complete -c netmask -s c -l cidr -d 'Output CIDR format address lists'
complete -c netmask -s i -l cisco -d 'Output Cisco style address lists'
complete -c netmask -s r -l range -d 'Output ip address ranges'
complete -c netmask -s x -l hex -d 'Output address/netmask pairs in hex'
complete -c netmask -s o -l octal -d 'Output address/netmask pairs in octal'
complete -c netmask -s b -l binary -d 'Output address/netmask pairs in binary'
complete -c netmask -s n -l nodns -d 'Disable DNS lookups for addresses DEFINITIONS A  spec  is an address specific…'

