# nfctool
# Autogenerated from man page /usr/share/man/man1/nfctool.1.gz
complete -c nfctool -s h -l help
complete -c nfctool -s v -l version
complete -c nfctool -s l -l list
complete -c nfctool -s d -l device
complete -c nfctool -s p -l poll
complete -c nfctool -s s -l set-param
complete -c nfctool -s k -l snl
complete -c nfctool -s n -l sniff
complete -c nfctool -s a -l snapshot-len
complete -c nfctool -s y -l dump-symm
complete -c nfctool -s t -l show-timestamp
complete -c nfctool -s f -l pcap-file

