# nohang
# Autogenerated from man page /usr/share/man/man8/nohang.8.gz
complete -c nohang -s h -l help
complete -c nohang -s v -l version
complete -c nohang -s m -l memload
complete -c nohang -s c -l config
complete -c nohang -l tasks -l check
complete -c nohang -l monitor

