# ntpshmmon
# Autogenerated from man page /usr/share/man/man1/ntpshmmon.1.gz
complete -c ntpshmmon -s '?' -s h -l help -d 'Display program usage and exit'
complete -c ntpshmmon -s n -l count -d 'Set maximum number of samples to collect to COUNT'
complete -c ntpshmmon -s o -l offset -d 'Replace the "Seen@" column with the "Offset" column'
complete -c ntpshmmon -s s -l rmshm -d 'Remove all SHM segments used by GPSD'
complete -c ntpshmmon -s t -l seconds -d 'Set maximum time to collect samples in seconds to SECONDS'
complete -c ntpshmmon -s v -l verbose -d 'Enable verbose status messages'
complete -c ntpshmmon -s V -l version -d 'Display program version and exit'

