# odbc_config
# Autogenerated from man page /usr/share/man/man1/odbc_config.1.gz
complete -c odbc_config -l prefix -d 'Prefix for architecture-independent file tree'
complete -c odbc_config -l exec-prefix -d 'Prefix for architecture-dependent file tree'
complete -c odbc_config -l include-prefix -d 'Directory with C header files for unixODBC'
complete -c odbc_config -l lib-prefix -d 'Directory with object code (. so) libraries'
complete -c odbc_config -l bin-prefix -d 'Location of user executables'
complete -c odbc_config -l version -d 'unixODBC version'
complete -c odbc_config -l libs -d 'Compiler flags for linking dynamic libraries'
complete -c odbc_config -l static-libs -d 'Absolute file name of static unixODBC library'
complete -c odbc_config -l libtool-libs -d 'Absolute file name of libtool unixODBC library'
complete -c odbc_config -l cflags -d 'Compiler flags to find include files and critical compiler flags and defines …'
complete -c odbc_config -l odbcversion -d 'Version of the ODBC specification used by the unixODBC'
complete -c odbc_config -l odbcini -d 'Absolute file name of the system-wide DSN configuration file R odbc. ini '
complete -c odbc_config -l odbcinstini -d 'Absolute file name of the driver configuration file R odbcinst. ini '
complete -c odbc_config -l header -d 'Definitions of used C preprocessor constants'
complete -c odbc_config -l ulen -d 'Compiler flag for defining SIZEOF_SQLULEN '

