# odbcinst
# Autogenerated from man page /usr/share/man/man1/odbcinst.1.gz
complete -c odbcinst -s i -d 'Install (add section to config file) new OBJECT'
complete -c odbcinst -s u -d 'Uninstall (remove section from config file) existing OBJECT'
complete -c odbcinst -s q -d 'Query the config files and print the options for specified OBJECT'
complete -c odbcinst -s j -d 'Prints current configuration of unixODBC, listing (among others) the paths to…'
complete -c odbcinst -s c -d 'Calls SQLCreateDataSource'
complete -c odbcinst -s m -d 'Calls SQLManageDataSources'
complete -c odbcinst -l version -d 'Prints program version and exits. SS OBJECTS'
complete -c odbcinst -s d -d 'The ACTION affect drivers (and thus the odbcinst. ini configuration file)'
complete -c odbcinst -s s -d 'The ACTION affect data sources (and thus the user or system odbc'
complete -c odbcinst -s f -d 'The FILE is template file, describing the configuration of installed OBJECT (…'
complete -c odbcinst -s r -d 'Same as the -f OPTION, only take the standard input as the template file'
complete -c odbcinst -s n -d 'Specifies the NAME of the OBJECT'
complete -c odbcinst -s v -d 'Turn off verbose mode'
complete -c odbcinst -s l -d 'The specified data source is system-wide'
complete -c odbcinst -s h -d 'The specified data source is user-specific'

