# oom-sort
# Autogenerated from man page /usr/share/man/man1/oom-sort.1.gz
complete -c oom-sort -s h -l help
complete -c oom-sort -l num -s n
complete -c oom-sort -l len -s l
complete -c oom-sort -l sort -s s

