# pixiewps
# Autogenerated from man page /usr/share/man/man1/pixiewps.1.gz
complete -c pixiewps -s e -l pke -d 'Enrollee\'s DH public key, found in M1'
complete -c pixiewps -s r -l pkr -d 'Registrar\'s DH public key, found in M2'
complete -c pixiewps -s s -l e-hash1 -d 'Enrollee\'s hash 1, found in M3.  It\'s the hash of the first half of the PIN'
complete -c pixiewps -s z -l e-hash2 -d 'Enrollee\'s hash 2, found in M3.  It\'s the hash of the second half of the PIN'
complete -c pixiewps -s a -l authkey -d 'Authentication session key'
complete -c pixiewps -s n -l e-nonce -d 'Enrollee\'s nonce, found in M1'
complete -c pixiewps -s m -l r-nonce -d 'Registrar\'s nonce, found in M2'
complete -c pixiewps -s b -l e-bssid -d 'Enrollee\'s BSSID.  Used with other parameters to compute the session keys'
complete -c pixiewps -s S -l dh-small -d 'Small Diffie-Hellman keys.  The same option must be specified in Reaver too'
complete -c pixiewps -s v -l verbosity -d 'Verbosity level 1-3, 1 is quietest, default is 3'
complete -c pixiewps -s h -d 'Display a simple help usage screen'
complete -c pixiewps -l help -d 'Display verbose help'
complete -c pixiewps -s V -l version -d 'Display version and other information'
complete -c pixiewps -l mode -d 'Select modes, comma separated (experimental modes are not used unless specifi…'
complete -c pixiewps -l start
complete -c pixiewps -l end -d 'Starting and ending dates for mode 3, they are interchangeable'
complete -c pixiewps -s 7 -l m7-enc -d 'Encrypted settings, found in M7'
complete -c pixiewps -s 5 -l m5-enc -d 'Encrypted settings, found in M5.  Recover Enrollee\'s secret nonce 1'

