# pki
# Autogenerated from man page /usr/share/man/man1/pki.1.gz
complete -c pki -s h -l help -d 'Prints usage information and a short summary of the available commands'
complete -c pki -s g -l gen -d 'Generate a new private key'
complete -c pki -s s -l self -d 'Create a self-signed certificate'
complete -c pki -s i -l issue -d 'Issue a certificate using a CA certificate and key'
complete -c pki -s c -l signcrl -d 'Issue a CRL using a CA certificate and key'
complete -c pki -s z -l acert -d 'Issue an attribute certificate'
complete -c pki -s r -l req -d 'Create a PKCS#10 certificate request'
complete -c pki -s 7 -l pkcs7 -d 'Provides PKCS#7 wrap/unwrap functions'
complete -c pki -s k -l keyid -d 'Calculate key identifiers of a key or certificate'
complete -c pki -s a -l print -d 'Print a credential (key, certificate etc. ) in human readable form'
complete -c pki -s d -l dn -d 'Extract the subject DN of an X. 509 certificate'
complete -c pki -s p -l pub -d 'Extract a public key from a private key or certificate'
complete -c pki -s v -l verify -d 'Verify a certificate using a CA certificate'

