# proxytunnel
# Autogenerated from man page /usr/share/man/man1/proxytunnel.1.gz
complete -c proxytunnel -s i -l inetd -d 'Run from inetd (default: off)'
complete -c proxytunnel -s a -l standalone -d 'Run as standalone daemon on specified port'
complete -c proxytunnel -s p -l proxy -d 'Use host and port as the local proxy to connect to, if not specified the HTTP…'
complete -c proxytunnel -s r -l remproxy -d 'Use host and port as the remote (secondary) proxy to connect to'
complete -c proxytunnel -s d -l dest -d 'Use host and port as the destination for the tunnel, you can also specify the…'
complete -c proxytunnel -s e -l encrypt -d 'SSL encrypt data between local proxy and destination'
complete -c proxytunnel -s E -l encrypt-proxy -d 'SSL encrypt data between client and local proxy'
complete -c proxytunnel -s X -l encrypt-remproxy -d 'SSL encrypt data between local and remote (secondary) proxy'
complete -c proxytunnel -s W -l wa-bug-29744 -d 'If SSL is in use (by -e, -E, -X options), stop using it immediately after the…'
complete -c proxytunnel -s B -l buggy-encrypt-proxy -d 'Equivalent to -E -W.  (Provided for backwards compatibility. )'
complete -c proxytunnel -s F -l passfile
complete -c proxytunnel -s P -l proxyauth
complete -c proxytunnel -s R -l remproxyauth
complete -c proxytunnel -s N -l ntlm
complete -c proxytunnel -s t -l domain
complete -c proxytunnel -s H -l header
complete -c proxytunnel -s x -l proctitle
complete -c proxytunnel -s v -l verbose
complete -c proxytunnel -s q -l quiet
complete -c proxytunnel -s h -l help
complete -c proxytunnel -s V -l version

