# psi2log
# Autogenerated from man page /usr/share/man/man1/psi2log.1.gz
complete -c psi2log -s h -l help
complete -c psi2log -s t -l target
complete -c psi2log -s i -l interval
complete -c psi2log -s l -l log
complete -c psi2log -s m -l mode
complete -c psi2log -s s -l suppress-output

