# psk-crack
# Autogenerated from man page /usr/share/man/man1/psk-crack.1.gz
complete -c psk-crack -l help -s h -d 'Display this usage message and exit'
complete -c psk-crack -l version -s V -d 'Display program version and exit'
complete -c psk-crack -l verbose -s v -d 'Display verbose progress messages'
complete -c psk-crack -l dictionary -s d -d 'Set dictionary file to <f>'
complete -c psk-crack -l norteluser -s u -d 'Specify the username for Nortel Contivity cracking'
complete -c psk-crack -l bruteforce -s B -d 'Select bruteforce cracking up to <n> characters'
complete -c psk-crack -l pskcrack -d option
complete -c psk-crack -l charset -s c -d 'Set bruteforce character set to <s> Default is "0123456789abcdefghijklmnopqrs…'

