# pw-inspector
# Autogenerated from man page /usr/share/man/man1/pw-inspector.1.gz
complete -c pw-inspector -s i -d 'file to read passwords from (default: stdin)'
complete -c pw-inspector -s o -d 'file to write valid passwords to (default: stdout)'
complete -c pw-inspector -s m -d 'minimum length of a valid password'
complete -c pw-inspector -s M -d 'maximum length of a valid password'
complete -c pw-inspector -s c -d 'the minimum number of sets required (default: all given)'
complete -c pw-inspector -s h -l help -d 'Show summary of options.  SETS'
complete -c pw-inspector -s l -d 'lowcase characters (a,b,c,d, etc. )'
complete -c pw-inspector -s u -d 'upcase characters (A,B,C,D, etc. )'
complete -c pw-inspector -s n -d 'numbers (1,2,3,4, etc. )'
complete -c pw-inspector -s p -d 'printable characters (which are not -l/-n/-p, e. g.  $,!,/,(,*, etc. )'

