# r2pm
# Autogenerated from man page /usr/share/man/man1/r2pm.1.gz
complete -c r2pm -s a -d 'Adds an external r2pm repository, no arguments to -a will list all the regist…'
complete -c r2pm -s I -d 'Show information about repository and installed packages'
complete -c r2pm -s i -d 'Install a package'
complete -c r2pm -o gi -d 'Install a package in the system directory'
complete -c r2pm -s t -d 'Show last build + testsuite run from travis, greps for errors'
complete -c r2pm -s u -d 'Uninstall a package'
complete -c r2pm -o gu -d 'Uninstall a package from the system directory'
complete -c r2pm -s l -d 'List installed packages'
complete -c r2pm -s s -d 'Search in database for packages matching keyword'
complete -c r2pm -s r -d 'Run command with R2PM_BINDIR in PATH'
complete -c r2pm -s v -d 'Show version information'
complete -c r2pm -s h -d 'Show usage help message'
complete -c r2pm -s c -d 'Clean the source cache'
complete -c r2pm -s w -d 'Show when a package was installed or exit 1 if pkg does not exist El EXAMPLES…'

