# reaver
# Autogenerated from man page /usr/share/man/man1/reaver.1.gz
complete -c reaver -s m -l mac
complete -c reaver -s e -l essid
complete -c reaver -s c -l channel
complete -c reaver -s o -l out-file
complete -c reaver -s f -l fixed
complete -c reaver -s 5 -l 5ghz
complete -c reaver -s v -l verbose
complete -c reaver -s q -l quiet
complete -c reaver -s i -l interface
complete -c reaver -s b -l bssid
complete -c reaver -s p -l pin
complete -c reaver -s h -l help

