# samdump2
# Autogenerated from man page /usr/share/man/man1/samdump2.1.gz
complete -c samdump2 -s d -d 'enable debugging'
complete -c samdump2 -s h -d 'display this help'
complete -c samdump2 -s o -d 'write output to file EXAMPLE samdump2 -o out /mnt/ntfs/WINDOWS/system32/confi…'

