# scalpel
# Autogenerated from man page /usr/share/man/man1/scalpel.1.gz
complete -c scalpel -s b -d 'Carve files even if defined footers aren\'t discovered within maximum carve si…'
complete -c scalpel -s c -d 'Chooses which configuration file to use'
complete -c scalpel -s d -d 'Generate header/footer database'
complete -c scalpel -s e -d 'Do nested header/footer matching, to deal with structured files that may cont…'
complete -c scalpel -s h -d 'Show a help screen and exit'
complete -c scalpel -s i -d 'file is used as a list of input files to examine'
complete -c scalpel -s o -d 'Recovered files are written to the directory directory'
complete -c scalpel -s n -d 'Don\'t add extensions to extracted files'
complete -c scalpel -s O -d 'Don\'t organize carved files by type'
complete -c scalpel -s p -d 'Perform an image file preview'
complete -c scalpel -s q -d 'Carve files only when the header is cluster-aligned'
complete -c scalpel -s r -d 'Find only first of overlapping headers/footers [foremost 0. 69 compat mode]'
complete -c scalpel -s V -d 'Show copyright information and exit'
complete -c scalpel -s v -d 'Enables verbose mode'

