# scepclient
# Autogenerated from man page /usr/share/man/man8/scepclient.8.gz
complete -c scepclient -s v -l version
complete -c scepclient -s h -l help
complete -c scepclient -s u -l url
complete -c scepclient -s + -l optionsfrom
complete -c scepclient -s f -l force
complete -c scepclient -s q -l quiet
complete -c scepclient -s o -l out
complete -c scepclient -s i -l in
complete -c scepclient -s k -l keylength
complete -c scepclient -s D -l days
complete -c scepclient -s S -l startdate
complete -c scepclient -s E -l enddate
complete -c scepclient -s d -l dn
complete -c scepclient -s s -l subjectAltName
complete -c scepclient -s p -l password
complete -c scepclient -s a -l algorithm
complete -c scepclient -s m -l method
complete -c scepclient -s t -l interval
complete -c scepclient -s x -l maxpolltime
complete -c scepclient -s l -l debug

