# scrounge-ntfs
# Autogenerated from man page /usr/share/man/man8/scrounge-ntfs.8.gz
complete -c scrounge-ntfs -s c -d 'The cluster size (in sectors).  When not specified a default of 8 is used'
complete -c scrounge-ntfs -s l -d 'List partition information for a drive'
complete -c scrounge-ntfs -s m -d 'When recovering data this specifies the location of the MFT from the beginnin…'
complete -c scrounge-ntfs -s o -d 'Directory to put rescued files in'
complete -c scrounge-ntfs -s s -d 'Search disk for partition information.  (Not implemented yet)'

