# smem-secure-delete
# Autogenerated from man page /usr/share/man/man1/smem-secure-delete.1.gz
complete -c smem-secure-delete -s f -d 'fast (and insecure mode): no /dev/urandom'
complete -c smem-secure-delete -s l -d 'lessens the security'
complete -c smem-secure-delete -s v -d 'verbose mode BEWARE'

