# sploitctl
# Autogenerated from man page /usr/share/man/man1/sploitctl.1.gz
complete -c sploitctl -s f -d '      - ? to list sites'
complete -c sploitctl -s u -d '      - ? to list sites'
complete -c sploitctl -s d
complete -c sploitctl -s s
complete -c sploitctl -s t
complete -c sploitctl -s r
complete -c sploitctl -s A
complete -c sploitctl -s P
complete -c sploitctl -s X
complete -c sploitctl -s R -d MISC
complete -c sploitctl -s V
complete -c sploitctl -s H -d 'EXAMPLES # download and decompress all exploit archives and remove archive'

