# srm
# Autogenerated from man page /usr/share/man/man1/srm.1.gz
complete -c srm -s d -d 'ignore the two special dot files .  and .  on the commandline'
complete -c srm -s f -d 'fast (and insecure mode): no /dev/urandom, no synchronize mode'
complete -c srm -s l -d 'lessens the security'
complete -c srm -s r -d 'recursive mode, deletes all subdirectories'
complete -c srm -s v -d 'verbose mode'
complete -c srm -s z -d 'wipes the last write with zeros instead of random data LIMITATIONS'

