# ssldump
# Autogenerated from man page /usr/man/man1/ssldump.1.gz
complete -c ssldump -s A -d 'Print all record fields (by default ssldump chooses the most interesting fiel…'
complete -c ssldump -s d -d 'Display the application data traffic'
complete -c ssldump -s e -d 'Print absolute timestamps instead of relative timestamps'
complete -c ssldump -s r -d 'Read data from file instead of from the network'
complete -c ssldump -s k -d 'Use keyfile as the location of the SSL keyfile (OpenSSL format) Previous vers…'
complete -c ssldump -s n -d 'Don\'t try to resolve host names from IP addresses'
complete -c ssldump -s N -d 'Attempt to parse ASN. 1 when it appears, such as in  certificates and DNs'
complete -c ssldump -s p -d 'Use password as the SSL keyfile password'
complete -c ssldump -s P -d 'Don\'t put the interface into promiscuous mode'
complete -c ssldump -s q -d 'Don\'t decode any record fields beyond a single summary line.  (quiet mode)'
complete -c ssldump -s x -d 'Print each record in hex, as well as decoding it'
complete -c ssldump -s X -d 'When the -d option is used, binary data is automatically printed in two colum…'
complete -c ssldump -s a -d 'Print bare TCP ACKs (useful for observing Nagle behavior)'
complete -c ssldump -s H -d 'Print the full SSL packet header'
complete -c ssldump -s y -d 'Decorate the output for processing with troff'

