# sswap
# Autogenerated from man page /usr/share/man/man1/sswap.1.gz
complete -c sswap -s f -d 'fast (and insecure mode): no /dev/urandom, no synchronize mode'
complete -c sswap -s l -d 'lessens the security'
complete -c sswap -s v -d 'verbose mode'
complete -c sswap -s z -d 'wipes the last write with zeros instead of random data BEWARE'

