# stunnel
# Autogenerated from man page /usr/share/man/man8/stunnel.8.gz
complete -c stunnel -o fd -d 'Read the config file from specified file descriptor'
complete -c stunnel -o help -d 'Print stunnel help menu'
complete -c stunnel -o version -d 'Print stunnel version and compile time defaults'
complete -c stunnel -o sockets -d 'Print default socket options'
complete -c stunnel -o options -d 'Print supported \\s-1TLS\\s0 options'
complete -c stunnel -o install -d 'Install \\s-1NT\\s0 Service'
complete -c stunnel -o uninstall -d 'Uninstall \\s-1NT\\s0 Service'
complete -c stunnel -o start -d 'Start \\s-1NT\\s0 Service'
complete -c stunnel -o stop -d 'Stop \\s-1NT\\s0 Service'
complete -c stunnel -o reload -d 'Reload the configuration file of the running \\s-1NT\\s0 Service'
complete -c stunnel -o reopen -d 'Reopen the log file of the running \\s-1NT\\s0 Service'
complete -c stunnel -o exit -d 'Exit an already started stunnel'

