# thc-ipv6
# Autogenerated from man page /usr/share/man/man8/thc-ipv6.8.gz
complete -c thc-ipv6 -s t -d 'Enumerates a domain for DNS entries, it uses a dictionary file if supplied or…'
complete -c thc-ipv6 -s s -s d -d 'The hello command takes optionally the DR priority (default: 0)'
complete -c thc-ipv6 -s T -s p -s 1 -s 2 -s 3 -s 4 -s 5 -s 6 -s 7 -d 'Fuzzes an icmp6 packet'
complete -c thc-ipv6 -s e -s 8 -d 'Fuzzes a DHCPv6 server on specified packet types'
complete -c thc-ipv6 -s h -d 'Note that on Debian (if you read this on Debian) command names are prefixed w…'
complete -c thc-ipv6 -s a
complete -c thc-ipv6 -s c
complete -c thc-ipv6 -s P
complete -c thc-ipv6 -s U
complete -c thc-ipv6 -s r
complete -c thc-ipv6 -s R

