# ubxtool
# Autogenerated from man page /usr/share/man/man1/ubxtool.1.gz
complete -c ubxtool -s '?' -s h -l help -d 'Makes ubxtool print a usage message and exit'
complete -c ubxtool -s c -l command -d 'Send a command to the GPS'
complete -c ubxtool -l device -d 'The DEVICE on the gpsd to connect to.  Defaults to all'
complete -c ubxtool -s e -l enable -d 'Enable an option in the GPS'
complete -c ubxtool -s f -l file -d 'Connect to a file or device'
complete -c ubxtool -s g -l getitem -d 'Get the value of ITEM from LAYER, starting at POSITION, up to END key/value p…'
complete -c ubxtool -l host -d 'Connect to the gpsd on HOST (server).  Defaults to localhost'
complete -c ubxtool -s i -l portid -d 'Specifies port ID # (interface) for port-related commands such as UBX_CFG-PRT'
complete -c ubxtool -l port -d 'Use PORT to connect to gpsd.  Defaults to 2947'
complete -c ubxtool -s P -l protver -d 'Sets the protocol version to use for sending commands.  Minimum 6 (Antaris 4)'
complete -c ubxtool -s r -o readonly -d 'Read only.  Do not send anything to the GPS'
complete -c ubxtool -s R -l rawfile -d 'Save all raw serial data received from the GPS into the file RAW'
complete -c ubxtool -s s -l inspeed -d 'Set local serial port speed to SPEED bps.  Default 9,600 bps'
complete -c ubxtool -s S -l setspeed -d 'Set the GPS serial port speed to SPEED bps'
complete -c ubxtool -s t -l timestamp -d 'Timestamp decoded messages with seconds since the epoch'
complete -c ubxtool -s v -l verbosity -d 'Set verbosity level to VERBOSITY'
complete -c ubxtool -s V -l version -d 'Print ubxtool version and exit'
complete -c ubxtool -s w -l wait -d 'Wait for WAIT seconds before exiting.  Default 2 seconds'
complete -c ubxtool -s x -l delitem -d 'Delete the value of ITEM name from LAYERS.  The bit map LAYERS is optional'
complete -c ubxtool -s z -l setitem -d 'Set the value of ITEM name to VAL in LAYERS in the GPS (UBX-CFG-VALSET)'
complete -c ubxtool -s d -l disable
complete -c ubxtool -s p -l preset

