# uic-qt3
# Autogenerated from man page /usr/share/man/man1/uic-qt3.1.gz
complete -c uic-qt3 -s o -d 'Write output to file rather than to stdout'
complete -c uic-qt3 -o nofwd -d 'Omit forward declarations of custom classes in the generated header file'
complete -c uic-qt3 -o tr -d 'Use func() instead of tr() for internationalization'
complete -c uic-qt3 -o version -d 'Display the version of uic and exit'

