# vi
# Autogenerated from man page /usr/share/man/man1/vi.1p.gz
complete -c vi -o ccommand -d 'See the R ex command description of the  -c option'
complete -c vi -s r -d 'See the R ex command description of the  -r option'
complete -c vi -s R -d 'See the R ex command description of the  -R option'
complete -c vi -o ttagstring -d 'See the R ex command description of the  -t option'
complete -c vi -s c -d 'See the ex command description of the'
complete -c vi -s t -d 'See the ex command description of the'
complete -c vi -s w -d 'See the ex command description of the'
complete -c vi -s 1 -d 'error.   b'
complete -c vi -s 2 -d 'follows, and the window edit option shall not be affected'
complete -c vi -s D -d 'can result in a completely changed screen, without any overlap'

