# wordlistctl
# Autogenerated from man page /usr/share/man/man1/wordlistctl.1.gz
complete -c wordlistctl -s h -l help
complete -c wordlistctl -s v -l version
complete -c wordlistctl -s b -l basedir -d '                     (default: /usr/share/wordlists/)'
complete -c wordlistctl -s d -l decompress
complete -c wordlistctl -s g -l group -d '                     Available Groups are:                          usernames…'
complete -c wordlistctl -s l -l wordlist
complete -c wordlistctl -s u -l useragent
complete -c wordlistctl -s w -l workers
complete -c wordlistctl -l local

