# xgps
# Autogenerated from man page /usr/share/man/man1/xgps.1.gz
complete -c xgps -s '?' -s h -l help
complete -c xgps -o device
complete -c xgps -s D -l debug
complete -c xgps -l host
complete -c xgps -s p -l port
complete -c xgps -s V -l version
complete -c xgps -s l -l llfmt
complete -c xgps -s r -l rotate
complete -c xgps -s u -l units -d option
complete -c xgps -l nautical -d 'option forces this mode.  The'
complete -c xgps -l landspeed -d 'option produces a simple speedometer'
complete -c xgps -l speedunits -d 'option can be used to set the speed units for display; follow the keyword wit…'
complete -c xgps -l maxspeed -d 'sets the maximum on the speedometer.  ENVIRONMENT'

