# zerk
# Autogenerated from man page /usr/share/man/man1/zerk.1.gz
complete -c zerk -s '?' -s h -d 'Makes zerk print a usage message and exit'
complete -c zerk -s c -d 'Send a text string to the GPS'
complete -c zerk -s e -d 'Enable an option in the GPS'
complete -c zerk -s f -d 'Connect to a file or device'
complete -c zerk -s O -d 'Load an Option Authorization File (OAF) into the GPS'
complete -c zerk -s r -d 'Read only.  Do not send anything to the GPS'
complete -c zerk -s R -d 'Save all raw data from the GPS into the file RAW'
complete -c zerk -s S -d 'Configure the GPS serial speed to SPEED bps'
complete -c zerk -s s -d 'Set local serial port speed to SPEED bps.  Default 115,200 bps'
complete -c zerk -s V -d 'Print zerk version and exit'
complete -c zerk -s v -d 'Set verbosity level to VERBOSITY'
complete -c zerk -s W -d 'Force waiting the entire wait time'
complete -c zerk -s w -d 'Wait for WAIT seconds before exiting'
complete -c zerk -s d
complete -c zerk -s p

