// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1619467227);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1619457023);
user_pref("app.update.lastUpdateTime.region-update-timer", 1619467467);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1619457143);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1619467107);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1619467347);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.contentblocking.category", "custom");
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.migration.version", 107);
user_pref("browser.newtab.extensionControlled", true);
user_pref("browser.newtab.privateAllowed", false);
user_pref("browser.newtabpage.activity-stream.impressionId", "{82be6062-6ebd-4285-b594-a156ee0a84a5}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"canvasblocker_kkapsner_de\"],\"idsInUrlbar\":[\"canvasblocker_kkapsner_de\",\"bookmark\"],\"idsInUrlbarPreProton\":[\"canvasblocker_kkapsner_de\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.policies.applied", true);
user_pref("browser.policies.runOncePerModification.addSearchEngines", "[\"Garuda searX\",\"Whoogle (local - needs 'whoogle' installed)\",\"Searx (local - needs 'searx' installed)\",\"DuckDuckGo Lite\"]");
user_pref("browser.policies.runOncePerModification.extensionsInstall", "[\"https://addons.mozilla.org/firefox/downloads/file/3365502/sweet_dark-4.0-an+fx.xpi\",\"https://addons.cdn.mozilla.net/user-media/addons/607454/ublock_origin-1.35.0-an+fx.xpi\",\"https://addons.mozilla.org/firefox/downloads/file/3711139/canvasblocker-1.5-an+fx.xpi\",\"https://addons.mozilla.org/firefox/downloads/file/3748919/clearurls-1.21.0-an+fx.xpi\",\"https://addons.mozilla.org/firefox/downloads/file/3712931/dark_reader-4.9.29-an+fx.xpi\",\"https://addons.mozilla.org/firefox/downloads/file/3716637/tabliss_new_tab-2.1.0-fx.xpi\"]");
user_pref("browser.policies.runOncePerModification.extensionsUninstall", "[\"google@search.mozilla.org\",\"bing@search.mozilla.org\",\"amazondotcom@search.mozilla.org\",\"ebay@search.mozilla.org\",\"twitter@search.mozilla.org\"]");
user_pref("browser.policies.runOncePerModification.removeSearchEngines", "[\"Google\",\"Bing\",\"Amazon.com\",\"eBay\",\"Twitter\"]");
user_pref("browser.policies.runOncePerModification.setDefaultSearchEngine", "Garuda searX");
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.first-seen", 1619467469);
user_pref("browser.region.update.region", "IN");
user_pref("browser.region.update.updated", 1619467469);
user_pref("browser.shell.mostRecentDateSetAsDefault", "1619467084");
user_pref("browser.slowStartup.averageTime", 1873);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.lastColdStartupCheck", 1619467082);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"_73a6fe31-595d-460b-a920-fcc0f8843232_-browser-action\",\"canvasblocker_kkapsner_de-browser-action\",\"addon_darkreader_org-browser-action\",\"ublock0_raymondhill_net-browser-action\",\"_74145f27-f039-47ce-a470-a662b129930a_-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"developer-button\",\"_73a6fe31-595d-460b-a920-fcc0f8843232_-browser-action\",\"canvasblocker_kkapsner_de-browser-action\",\"addon_darkreader_org-browser-action\",\"ublock0_raymondhill_net-browser-action\",\"_74145f27-f039-47ce-a470-a662b129930a_-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("distribution.garudalinux.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "88.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("extensions.activeThemeID", "{59f619c8-220b-4a27-8918-bf1537bc060a}");
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20210424113327");
user_pref("extensions.lastAppVersion", "88.0");
user_pref("extensions.lastPlatformVersion", "88.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.CanvasBlocker@kkapsner.de", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.addon@darkreader.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.extension@tabliss.io", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.uBlock0@raymondhill.net", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.{73a6fe31-595d-460b-a920-fcc0f8843232}", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.{74145f27-f039-47ce-a470-a662b129930a}", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"81b2f34b-c400-4fce-9e97-fda67b395fbe\",\"screenshots@mozilla.org\":\"7aa60b92-7a84-4632-96f7-9f4f71c3f52c\",\"default-theme@mozilla.org\":\"e4219a59-e6be-405f-aaf3-8225f4355d98\",\"google@search.mozilla.org\":\"3bfb696b-973f-430f-8596-16906e9a4aa9\",\"amazondotcom@search.mozilla.org\":\"ed7adb17-83ab-477d-91ef-4d4c82c8beb7\",\"wikipedia@search.mozilla.org\":\"a9ae152f-184a-40dd-87b4-37a33dec6ecb\",\"bing@search.mozilla.org\":\"7ed7b711-faae-4f58-8ad1-2563321f55cb\",\"ddg@search.mozilla.org\":\"961304e0-7e42-4639-a5c4-791b3911c980\",\"ebay@search.mozilla.org\":\"7505f9c8-d9fd-4d0e-b0ce-5468ddcfde4c\",\"{59f619c8-220b-4a27-8918-bf1537bc060a}\":\"2f767ac5-d704-4443-bb0d-ac014e6befd7\",\"extension@tabliss.io\":\"a8a9258d-24d7-444b-87a4-e1ce3cca7f83\",\"{73a6fe31-595d-460b-a920-fcc0f8843232}\":\"dc3762f7-83ff-4861-af0e-0927a4433f2a\",\"CanvasBlocker@kkapsner.de\":\"893586e1-41c3-435f-8b3a-5d59b3d3edd5\",\"addon@darkreader.org\":\"ae9514dd-f8b0-4160-88ae-303c73db76ee\",\"uBlock0@raymondhill.net\":\"b782d2bc-17cc-4225-968e-815b0bd4aa05\",\"pictureinpicture@mozilla.org\":\"5bacac1d-77a8-4cb2-b440-a56a88645aa1\",\"{74145f27-f039-47ce-a470-a662b129930a}\":\"89c503fa-93fa-418f-ad02-710d6cfdac83\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1619457015);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("identity.sendtabpromo.url", "");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1619467556);
user_pref("media.gmp-gmpopenh264.version", "1.8.1.1");
user_pref("media.gmp-manager.buildID", "20210424113327");
user_pref("media.gmp-manager.lastCheck", 1619467553);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("privacy.userContext.extension", "CanvasBlocker@kkapsner.de");
user_pref("security.sandbox.content.tempDirSuffix", "a192ffbb-9db6-459a-9f09-24e8cd2aaf23");
user_pref("security.sandbox.plugin.tempDirSuffix", "42a070de-af27-489a-8310-777639c7fe0c");
user_pref("signon.management.page.breach-alerts.enabled", false);
user_pref("signon.management.page.breachAlertUrl", "");
user_pref("signon.management.page.mobileAndroidURL", "");
user_pref("signon.management.page.mobileAppleURL", "");
user_pref("startup.homepage_override_url", "http://localhost:5000/");
user_pref("startup.homepage_welcome_url", "http://localhost:5000/");
user_pref("startup.homepage_welcome_url.additional", "");
user_pref("toolkit.startup.last_success", 1619467074);
user_pref("toolkit.telemetry.cachedClientID", "fbe30e40-9ed1-4760-9de0-46e5fd494586");
